# Generated by Django 3.2 on 2021-12-14 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("savings", "0002_extend_emotion_length"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Transaction",
            new_name="StockTransaction",
        ),
        migrations.AlterModelTable(
            name="stock",
            table="stocks",
        ),
        migrations.AlterModelTable(
            name="stocktransaction",
            table="stock_transactions",
        ),
    ]
