# Generated by Django 3.1.4 on 2021-02-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="emotion",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
