# Generated by Django 3.1.4 on 2020-12-26 13:18

from django.db import migrations, models
import django.db.models.deletion
import savings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', savings.models.MonetaryField(decimal_places=10, max_digits=19)),
                ('strike_price', savings.models.MonetaryField(decimal_places=10, max_digits=19)),
                ('units', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='savings.stock')),
            ],
        ),
    ]
