# Generated by Django 3.1.4 on 2020-12-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0002_auto_20201227_0925"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="ticker",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
