# Generated by Django 3.1.4 on 2020-12-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0003_auto_20201227_1036"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="value",
        ),
    ]
