# Generated by Django 3.1.4 on 2020-12-29 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0004_remove_transaction_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="currency",
            field=models.CharField(default="BRL", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="logo_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="units",
            field=models.FloatField(),
        ),
    ]
